"""edit user tabel

Revision ID: 4ef61bb62464
Revises: 27709918b6c6
Create Date: 2024-01-16 17:38:31.186635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ef61bb62464'
down_revision = '27709918b6c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.drop_column('dosen_satu')
        batch_op.drop_column('dosen_dua')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.BigInteger(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('level')

    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dosen_dua', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dosen_satu', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
