"""buat table mahasiswa

Revision ID: 6612f52a9ac9
Revises: 5e55640212d9
Create Date: 2024-01-15 19:50:43.669569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6612f52a9ac9'
down_revision = '5e55640212d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dosen', schema=None) as batch_op:
        batch_op.alter_column('alamat',
               existing_type=mysql.VARCHAR(length=13),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.alter_column('alamat',
               existing_type=mysql.VARCHAR(length=13),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.alter_column('alamat',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=13),
               existing_nullable=False)

    with op.batch_alter_table('dosen', schema=None) as batch_op:
        batch_op.alter_column('alamat',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=13),
               existing_nullable=False)

    # ### end Alembic commands ###
