"""edit user tabel

Revision ID: 75ed32b6c387
Revises: 4ef61bb62464
Create Date: 2024-01-16 17:39:34.375592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ed32b6c387'
down_revision = '4ef61bb62464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dosen_satu', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('dosen_dua', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'dosen', ['dosen_dua'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'dosen', ['dosen_satu'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dosen_dua')
        batch_op.drop_column('dosen_satu')

    # ### end Alembic commands ###
